package content

import (
	"encoding/base64"
	"fmt"
	"os"
	"strings"
	"testing"

	"fbc/common"
	"fbc/state"
)

func TestPrepareNoCover(t *testing.T) {
	formats := []common.OutputFmt{
		common.OutputFmtEpub2, common.OutputFmtEpub3, common.OutputFmtKepub, common.OutputFmtKepub3,
		common.OutputFmtPdf, common.OutputFmtTxt, common.OutputFmtMd, common.OutputFmtKfx, common.OutputFmtAzw8,
	}
	tests := []struct {
		name     string
		noCover  bool
		existing bool
		generate bool
		reused   bool
	}{
		{name: "omit existing", noCover: true, existing: true},
		{name: "omit existing with fallback enabled", noCover: true, existing: true, generate: true},
		{name: "omit generated", noCover: true, generate: true},
		{name: "preserve body illustration", noCover: true, existing: true, reused: true},
		{name: "keep existing by default", existing: true},
		{name: "keep generated by default", generate: true},
	}
	for _, format := range formats {
		t.Run(format.String(), func(t *testing.T) {
			for _, tt := range tests {
				t.Run(tt.name, func(t *testing.T) {
					_, ctx := setupTestContent(t)
					env := state.EnvFromContext(ctx)
					env.NoCover = tt.noCover
					env.Cfg.Document.Images.Cover.Generate = tt.generate
					env.Cfg.Document.Images.Cover.Resize = common.ImageResizeModeNone
					env.DefaultCover = createTestJPEG(t, 20, 30, 90)
					var coverpage, binaries, bodyImage string
					if tt.existing {
						coverpage = `<coverpage><image l:href="#cover"/><image l:href="#cover2"/></coverpage>`
						data := base64.StdEncoding.EncodeToString(env.DefaultCover)
						for _, id := range []string{"cover", "cover2"} {
							binaries += fmt.Sprintf(`<binary id="%s" content-type="image/jpeg">%s</binary>`, id, data)
						}
					}
					if tt.reused {
						bodyImage = `<image l:href="#cover"/>`
					}
					src := fmt.Sprintf(`<FictionBook xmlns="http://www.gribuser.ru/xml/fictionbook/2.0"
						xmlns:l="http://www.w3.org/1999/xlink">
						<description><title-info><book-title>Cover test</book-title>%s<lang>en</lang></title-info>
						<document-info><id>00000000-0000-0000-0000-000000000001</id></document-info></description>
						<body><section><p>Content</p>%s</section></body>%s</FictionBook>`, coverpage, bodyImage, binaries)
					c, err := Prepare(ctx, strings.NewReader(src), "cover.fb2", format, env.Log)
					if err != nil {
						t.Fatalf("Prepare: %v", err)
					}
					t.Cleanup(func() {
						if err := os.RemoveAll(c.WorkDir); err != nil {
							t.Errorf("remove work directory: %v", err)
						}
					})

					omit := tt.noCover && !format.ForKindle()
					if got, want := c.CoverID != "", !omit; got != want {
						t.Fatalf("has cover = %v, want %v", got, want)
					}
					if !omit {
						if c.ImagesIndex[c.CoverID] == nil {
							t.Fatal("cover image is missing")
						}
						return
					}
					if len(c.Book.Description.TitleInfo.Coverpage) != 0 {
						t.Fatal("cover references remain")
					}
					for _, refs := range c.LinksRevIndex {
						for _, ref := range refs {
							if ref.Type == "coverpage" {
								t.Fatal("cover reference remains in link index")
							}
						}
					}
					wantImages := 0
					if tt.reused {
						wantImages = 1
						if c.ImagesIndex["cover"] == nil {
							t.Fatal("body illustration was removed")
						}
					}
					if len(c.ImagesIndex) != wantImages {
						t.Errorf("images = %d, want %d", len(c.ImagesIndex), wantImages)
					}
					if len(c.Book.Binaries) != wantImages {
						t.Errorf("binaries = %d, want %d; omitted cover binaries remain", len(c.Book.Binaries), wantImages)
					}
				})
			}
		})
	}
}
