package kfx

// Style fragment ($157) generation for KFX.
// Styles define formatting properties applied to content elements.
// Each style is referenced by name (symbol) in content entries.

// Unit types for dimension values
const (
	SymUnitRatio = 310 // ratio (relative, like 1.2)
	SymUnitEM    = 308 // em (font-relative)
	SymUnitPT    = 318 // pt (points)
	SymUnitPX    = 319 // px (pixels)
	SymUnitPct   = 314 // percent
)

// Text alignment values
const (
	SymAlignCenter  = 320 // center
	SymAlignJustify = 321 // justify
	SymAlignStart   = 324 // start (left in LTR)
	SymAlignEnd     = 325 // end (right in LTR)
)

// Font style/weight values
const (
	SymFontNormal    = 350 // normal
	SymFontBold      = 361 // bold
	SymFontItalic    = 382 // italic
	SymFontSemibold  = 362 // semibold
	SymFontLight     = 363 // light
	SymFontMedium    = 364 // medium
)

// StyleDef defines a KFX style with its properties.
type StyleDef struct {
	Name       string            // Style name (becomes local symbol)
	Parent     string            // Parent style name (for inheritance)
	Properties map[int]any       // KFX property symbol -> value
}

// DimensionValue creates a dimension value with unit.
// Example: DimensionValue(1.2, SymUnitRatio) -> {$307: 1.2, $306: $310}
func DimensionValue(value float64, unit int) StructValue {
	return NewStruct().
		SetFloat(SymValue, value). // $307 = value
		SetSymbol(SymUnit, unit)   // $306 = unit
}

// StyleBuilder helps construct style definitions.
type StyleBuilder struct {
	name   string
	parent string
	props  map[int]any
}

// NewStyle creates a new style builder.
func NewStyle(name string) *StyleBuilder {
	return &StyleBuilder{
		name:  name,
		props: make(map[int]any),
	}
}

// Inherit sets the parent style for inheritance.
func (sb *StyleBuilder) Inherit(parentName string) *StyleBuilder {
	sb.parent = parentName
	return sb
}

// FontSize sets the font size.
func (sb *StyleBuilder) FontSize(value float64, unit int) *StyleBuilder {
	sb.props[SymFontSize] = DimensionValue(value, unit)
	return sb
}

// FontWeight sets the font weight (SymFontBold, SymFontNormal, etc.).
func (sb *StyleBuilder) FontWeight(weight int) *StyleBuilder {
	sb.props[SymFontWeight] = weight
	return sb
}

// FontStyle sets the font style (SymFontItalic, SymFontNormal, etc.).
func (sb *StyleBuilder) FontStyle(style int) *StyleBuilder {
	sb.props[SymFontStyle] = style
	return sb
}

// LineHeight sets the line height.
func (sb *StyleBuilder) LineHeight(value float64, unit int) *StyleBuilder {
	sb.props[SymLineHeight] = DimensionValue(value, unit)
	return sb
}

// TextAlign sets the text alignment.
func (sb *StyleBuilder) TextAlign(align int) *StyleBuilder {
	sb.props[SymTextAlignment] = align
	return sb
}

// TextIndent sets the first-line text indent.
func (sb *StyleBuilder) TextIndent(value float64, unit int) *StyleBuilder {
	sb.props[SymTextIndent] = DimensionValue(value, unit)
	return sb
}

// MarginTop sets the top margin.
func (sb *StyleBuilder) MarginTop(value float64, unit int) *StyleBuilder {
	sb.props[SymMarginTop] = DimensionValue(value, unit)
	return sb
}

// MarginBottom sets the bottom margin.
func (sb *StyleBuilder) MarginBottom(value float64, unit int) *StyleBuilder {
	sb.props[SymMarginBottom] = DimensionValue(value, unit)
	return sb
}

// MarginLeft sets the left margin.
func (sb *StyleBuilder) MarginLeft(value float64, unit int) *StyleBuilder {
	sb.props[SymMarginLeft] = DimensionValue(value, unit)
	return sb
}

// MarginRight sets the right margin.
func (sb *StyleBuilder) MarginRight(value float64, unit int) *StyleBuilder {
	sb.props[SymMarginRight] = DimensionValue(value, unit)
	return sb
}

// SpaceBefore sets space before the element.
func (sb *StyleBuilder) SpaceBefore(value float64, unit int) *StyleBuilder {
	sb.props[SymSpaceBefore] = DimensionValue(value, unit)
	return sb
}

// SpaceAfter sets space after the element.
func (sb *StyleBuilder) SpaceAfter(value float64, unit int) *StyleBuilder {
	sb.props[SymSpaceAfter] = DimensionValue(value, unit)
	return sb
}

// Build creates the StyleDef.
func (sb *StyleBuilder) Build() StyleDef {
	return StyleDef{
		Name:       sb.name,
		Parent:     sb.parent,
		Properties: sb.props,
	}
}

// BuildStyleFragment creates a $157 style fragment from a StyleDef.
func BuildStyleFragment(def StyleDef) *Fragment {
	style := NewStruct().
		Set(SymStyleName, SymbolByName(def.Name)) // $173 = style_name as symbol

	// Note: parent_style ($158) is valid but not commonly used in KFX files
	// generated by Kindle Previewer. For compatibility, we skip it.

	// Add all properties
	for sym, val := range def.Properties {
		style.Set(sym, val)
	}

	return &Fragment{
		FType:   SymStyle,
		FIDName: def.Name,
		Value:   style,
	}
}

// StyleRegistry manages style definitions and generates style fragments.
type StyleRegistry struct {
	styles map[string]StyleDef
	order  []string          // Preserve insertion order
	used   map[string]bool   // Track which styles are actually used
}

// NewStyleRegistry creates a new style registry.
func NewStyleRegistry() *StyleRegistry {
	return &StyleRegistry{
		styles: make(map[string]StyleDef),
		used:   make(map[string]bool),
	}
}

// Register adds a style to the registry.
func (sr *StyleRegistry) Register(def StyleDef) {
	if _, exists := sr.styles[def.Name]; !exists {
		sr.order = append(sr.order, def.Name)
	}
	sr.styles[def.Name] = def
}

// Get returns a style definition by name.
func (sr *StyleRegistry) Get(name string) (StyleDef, bool) {
	def, ok := sr.styles[name]
	return def, ok
}

// Names returns all registered style names in order.
func (sr *StyleRegistry) Names() []string {
	return sr.order
}

// EnsureStyle ensures a style exists, creating a minimal one if needed.
// Marks the style as used for output. This is used for dynamically 
// encountered styles from FB2 paragraphs.
func (sr *StyleRegistry) EnsureStyle(name string) {
	sr.used[name] = true
	if _, exists := sr.styles[name]; !exists {
		// Create a minimal style with default paragraph formatting
		sr.Register(NewStyle(name).
			LineHeight(1.2, SymUnitRatio).
			Build())
	}
}

// BuildFragments creates style fragments for all used styles.
// Only styles that were marked via EnsureStyle are included.
func (sr *StyleRegistry) BuildFragments() []*Fragment {
	fragments := make([]*Fragment, 0, len(sr.used))
	for _, name := range sr.order {
		if sr.used[name] {
			def := sr.styles[name]
			fragments = append(fragments, BuildStyleFragment(def))
		}
	}
	return fragments
}

// DefaultStyleRegistry returns a registry with default FB2-to-KFX styles.
// These styles map FB2 semantic elements to KFX formatting.
func DefaultStyleRegistry() *StyleRegistry {
	sr := NewStyleRegistry()

	// Base paragraph style
	sr.Register(NewStyle("paragraph").
		LineHeight(1.2, SymUnitRatio).
		TextIndent(1.5, SymUnitEM).
		TextAlign(SymAlignJustify).
		Build())

	// Heading styles (h1-h6)
	sr.Register(NewStyle("h1").
		FontSize(2.0, SymUnitEM).
		FontWeight(SymFontBold).
		LineHeight(1.2, SymUnitRatio).
		MarginTop(1.0, SymUnitEM).
		MarginBottom(0.5, SymUnitEM).
		TextAlign(SymAlignCenter).
		Build())

	sr.Register(NewStyle("h2").
		FontSize(1.5, SymUnitEM).
		FontWeight(SymFontBold).
		LineHeight(1.2, SymUnitRatio).
		MarginTop(0.8, SymUnitEM).
		MarginBottom(0.4, SymUnitEM).
		TextAlign(SymAlignCenter).
		Build())

	sr.Register(NewStyle("h3").
		FontSize(1.25, SymUnitEM).
		FontWeight(SymFontBold).
		LineHeight(1.2, SymUnitRatio).
		MarginTop(0.6, SymUnitEM).
		MarginBottom(0.3, SymUnitEM).
		Build())

	sr.Register(NewStyle("h4").
		FontSize(1.1, SymUnitEM).
		FontWeight(SymFontBold).
		LineHeight(1.2, SymUnitRatio).
		MarginTop(0.5, SymUnitEM).
		MarginBottom(0.25, SymUnitEM).
		Build())

	sr.Register(NewStyle("h5").
		FontSize(1.0, SymUnitEM).
		FontWeight(SymFontBold).
		LineHeight(1.2, SymUnitRatio).
		MarginTop(0.4, SymUnitEM).
		MarginBottom(0.2, SymUnitEM).
		Build())

	sr.Register(NewStyle("h6").
		FontSize(0.9, SymUnitEM).
		FontWeight(SymFontBold).
		LineHeight(1.2, SymUnitRatio).
		MarginTop(0.3, SymUnitEM).
		MarginBottom(0.15, SymUnitEM).
		Build())

	// Epigraph style
	sr.Register(NewStyle("epigraph").
		FontStyle(SymFontItalic).
		MarginLeft(2.0, SymUnitEM).
		MarginRight(2.0, SymUnitEM).
		MarginTop(1.0, SymUnitEM).
		MarginBottom(1.0, SymUnitEM).
		Build())

	// Text author style (for epigraphs, poems, cites)
	sr.Register(NewStyle("text-author").
		TextAlign(SymAlignEnd).
		FontStyle(SymFontItalic).
		MarginTop(0.5, SymUnitEM).
		Build())

	// Subtitle style
	sr.Register(NewStyle("subtitle").
		FontWeight(SymFontBold).
		TextAlign(SymAlignCenter).
		MarginTop(0.5, SymUnitEM).
		MarginBottom(0.5, SymUnitEM).
		Build())

	// Empty line / blank space style
	sr.Register(NewStyle("empty-line").
		MarginTop(1.0, SymUnitEM).
		Build())

	// Poem styles
	sr.Register(NewStyle("poem").
		MarginLeft(2.0, SymUnitEM).
		MarginTop(1.0, SymUnitEM).
		MarginBottom(1.0, SymUnitEM).
		Build())

	sr.Register(NewStyle("poem-title").
		Inherit("poem").
		FontWeight(SymFontBold).
		TextAlign(SymAlignCenter).
		Build())

	sr.Register(NewStyle("stanza").
		Inherit("poem").
		MarginTop(0.5, SymUnitEM).
		Build())

	sr.Register(NewStyle("verse").
		Inherit("poem").
		TextIndent(0, SymUnitEM).
		Build())

	// Citation style
	sr.Register(NewStyle("cite").
		MarginLeft(2.0, SymUnitEM).
		MarginRight(2.0, SymUnitEM).
		FontStyle(SymFontItalic).
		Build())

	// Table style
	sr.Register(NewStyle("table").
		MarginTop(1.0, SymUnitEM).
		MarginBottom(1.0, SymUnitEM).
		Build())

	// Inline styles for text formatting
	sr.Register(NewStyle("strong").
		FontWeight(SymFontBold).
		Build())

	sr.Register(NewStyle("emphasis").
		FontStyle(SymFontItalic).
		Build())

	sr.Register(NewStyle("strikethrough").
		// Note: strikethrough needs special handling with $27 property
		Build())

	// Footnote style
	sr.Register(NewStyle("footnote").
		FontSize(0.85, SymUnitEM).
		Build())

	// Annotation style
	sr.Register(NewStyle("annotation").
		FontStyle(SymFontItalic).
		MarginBottom(1.0, SymUnitEM).
		Build())

	return sr
}
